
project_id = "gbqjopccxdgayopxxukz"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[realtime]
enabled = true

[storage]
enabled = true

[auth]
enabled = true

[functions]
[functions.match-resume]
verify_jwt = true

[functions.match-resume-to-jobs]
verify_jwt = true